### ISSUE TITLE
when make trackmarkers always has follow problem

### ISSUE THREAD

**Issue by mmxuan18** [abhineet123/MTF#1]
![image](https://user-images.githubusercontent.com/6283983/30014112-07b99782-917d-11e7-960d-0bbbd9e006a2.png)
all abuout feature related class can't link，but testmtf and trackuavtrajectory is ok

**Comment by abhineet123** [comment]
Hi, Thanks for letting me know about the issue. This probably has something to do with missing OpenCV features.
Can you provide more details like the OpenCV and Visual studio versions you are using and whether OpenCV has the [nonfree](http://docs.opencv.org/2.4/modules/nonfree/doc/nonfree.html) module installed ?
Also, please try rebuilding the cmake files after turning off the "WITH_FEAT" option (in SM/SM.cmake) and let me know if this problem persists.

**Comment by abhineet123** [comment]
While examining issue #2, I found a bug in `Examples/Examples.cmake` that was including the `trackMarkers` example executable to the cmake project irrespective of whether or not the feature module was enabled even though it needs this module to work. I have fixed this now. 
Please pull the latest code, try compiling again and let me know if this problem persists.

**Comment by abhineet123** [comment]
Please let me know if your error has been resolved so this issue can be closed.

**Comment by abhineet123** [comment]
Closed due to lack of feedback and as being a probable duplicate of issue #2 .
