### ISSUE TITLE
testMTF not working - error while loading shared libraries

### ISSUE THREAD

**Issue by kneczaj** [abhineet123/MTF#10]
I am just trying to use your stuff, so I thought to run testMTF which looks like some HelloWorld looking at the name.

thats the result:
> kamil@kamil-VirtualBox ~/dev/MTF/build $ /usr/local/bin/testMTF 
/usr/local/bin/testMTF: error while loading shared libraries: libmtf_test.so: cannot open shared object file: No such file or directory

I have build the project with default values (so with FLANN, third party etc.) The `cmake ..` on below

> kamil@kamil-VirtualBox ~/dev/MTF/build $ cmake ..
-- The C compiler identification is GNU 6.2.0
-- The CXX compiler identification is GNU 6.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Found OpenCV: /usr/local (found version "3.2.0") 
-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   random
--   filesystem
--   system
-- Getting Eigen headers from: /usr/include/eigen3
-- Getting OpenCV headers from: /usr/local/include;/usr/local/include/opencv
-- Using OpenCV libraries: opencv_calib3d;opencv_core;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_aruco;opencv_bgsegm;opencv_bioinspired;opencv_ccalib;opencv_datasets;opencv_dnn;opencv_dpm;opencv_face;opencv_freetype;opencv_fuzzy;opencv_line_descriptor;opencv_optflow;opencv_phase_unwrapping;opencv_plot;opencv_reg;opencv_rgbd;opencv_saliency;opencv_stereo;opencv_structured_light;opencv_surface_matching;opencv_text;opencv_tracking;opencv_xfeatures2d;opencv_ximgproc;opencv_xobjdetect;opencv_xphoto
-- Getting Boost headers from: /usr/include
-- Getting Boost libraries from: /usr/lib/x86_64-linux-gnu
-- Using Boost libraries: /usr/lib/x86_64-linux-gnu/libboost_random.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_system.so
-- DFT disabled
-- PFSL3 disabled
-- Getting ViSP headers from: /usr/local/include;/usr/local/include;/usr/local/include/opencv;/usr/include/libxml2;/usr/include
-- Using ViSP libraries: visp_vs;visp_visual_features;visp_vision;visp_tt_mi;visp_tt;visp_me;visp_mbt;visp_klt;visp_blob;visp_sensor;visp_robot;visp_io;visp_gui;visp_detection;visp_core;visp_ar
-- GOTURN disabled
-- Xvision disabled
-- Enabled third party trackers: DSST/src/DSST;KCF/src/KCF;CMT/src/CMT;RCT/src/RCT;TLD/src/TLD;Struck/src/Struck;MIL/src/MIL;FRG/src/FRG;ViSP/src/ViSP
-- DFM disabled
-- OpenCV nonfree module not found so disabling the feature based grid tracker
-- RegNet disabled
-- Checking for module 'flann'
--   Found flann, version 1.8.4
-- FLANN_ROOT: 
-- Found FLANN: /usr/local/lib/libflann_cpp.so  
-- FLANN found (include: /usr/local/include, lib: optimized;/usr/local/lib/libflann_cpp.so;debug;/usr/local/lib/libflann_cpp.so)
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.8.16") 
-- Found HDF5 headers at: /usr/include/hdf5/serial
-- Found HDF5 C++ libraries: /usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.12+", minimum required is "2.7") 
-- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.12") 
-- Found NumPy: /home/kamil/.local/lib/python2.7/site-packages/numpy/core/include (found version "1.11.2") 
-- PYTHON_INCLUDE_DIRS: /usr/include/python2.7
-- PYTHON_LIBRARIES: /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- Could NOT find Matlab (missing:  Matlab_INCLUDE_DIRS Matlab_MEX_LIBRARY Matlab_MEX_EXTENSION MEX_COMPILER MX_LIBRARY) 
-- Matlab not found so mexMTF is disabled
        If Matlab is installed but not detected, mexMTF can be compiled by running the command in 'mtf_mex_cmd.txt' at the MATLAB prompt after:
         * removing all semi colons
         * replacing all occurences of the type '-l<full path to library>' with '<full path to library>'
         * replacing all occurences of the type '-l-L<path to library folder>' with '-L<path to library folder>'
-- MTF_COMPILETIME_FLAGS: -std=c++11
-- MTF_RUNTIME_FLAGS: -Wfatal-errors;-Wno-write-strings;-Wno-unused-result;-Wformat=0;-std=c++11;-O3;-msse2
-- MTF_DEFINITIIIONS: NDEBUG;EIGEN_NO_DEBUG;DISABLE_DFT;DISABLE_PFSL3;DISABLE_GOTURN;DISABLE_XVISION;DISABLE_DFM;DISABLE_FEAT;DISABLE_REGNET;DISABLE_SPI
-- CMAKE_CXX_FLAGS:  -fopenmp
-- CMAKE_C_FLAGS: 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kamil/dev/MTF/build

However the result of `make install` makes me thinking sth might gone wrong. Take a look at `Set runtime path of "/usr/local/lib/libmtf.so" to ""` lines. Shoudn't the runtime path be different from an empty string?

> kamil@kamil-VirtualBox ~/dev/MTF/build $ sudo make install
[sudo] password for kamil: 
Makefile:240: warning: overriding recipe for target 'all'
Makefile:127: warning: ignoring old recipe for target 'all'
Built target frg
Built target cmt
Built target cvblobs
Built target opentld
Built target struck
Built target mil
Built target mtf_test
[  2%] Built target frg
[  5%] Built target cmt
[  9%] Built target cvblobs
[ 17%] Built target opentld
[ 23%] Built target struck
[ 25%] Built target mil
[ 90%] Built target mtf
[ 91%] Built target pyMTF
[ 92%] Built target mtf_test
[ 93%] Built target testMTF
[ 94%] Built target extractPatch
[ 95%] Built target createMosaic
[ 97%] Built target trackUAVTrajectory
[ 98%] Built target runMTF
[100%] Built target generateSyntheticSeq
[100%] Built target all
Built target mtf
Built target testMTF
Built target extractPatch
Built target createMosaic
Built target trackUAVTrajectory
Built target runMTF
Built target generateSyntheticSeq
Built target pyMTF
Built target FragTrack
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/bin/runMTF
-- Set runtime path of "/usr/local/bin/runMTF" to ""
-- Installing: /usr/local/bin/trackUAVTrajectory
-- Set runtime path of "/usr/local/bin/trackUAVTrajectory" to ""
-- Installing: /usr/local/bin/extractPatch
-- Set runtime path of "/usr/local/bin/extractPatch" to ""
-- Installing: /usr/local/bin/generateSyntheticSeq
-- Set runtime path of "/usr/local/bin/generateSyntheticSeq" to ""
-- Installing: /usr/local/bin/createMosaic
-- Set runtime path of "/usr/local/bin/createMosaic" to ""
-- Installing: /usr/local/lib/python2.7/dist-packages/pyMTF.so
-- Set runtime path of "/usr/local/lib/python2.7/dist-packages/pyMTF.so" to ""
-- Installing: /usr/local/bin/testMTF
-- Set runtime path of "/usr/local/bin/testMTF" to ""
-- Installing: /usr/local/lib/libmtf_test.so
-- Set runtime path of "/usr/local/lib/libmtf_test.so" to ""
-- Installing: /usr/local/lib/libmtf.so
-- Set runtime path of "/usr/local/lib/libmtf.so" to ""
-- Up-to-date: /usr/local/include
-- Installing: /usr/local/include/mtf
-- Installing: /usr/local/include/mtf/pipeline.h
-- Installing: /usr/local/include/mtf/mtf.h
-- Installing: /usr/local/include/mtf/mtf_src.h
-- Installing: /usr/local/include/mtf/TrackerBase.h
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/mtf
-- Installing: /usr/local/include/mtf/ThirdParty
-- Installing: /usr/local/include/mtf/ThirdParty/DSST
-- Installing: /usr/local/include/mtf/ThirdParty/DSST/Params.h
-- Installing: /usr/local/include/mtf/ThirdParty/DSST/wrappers.h
-- Installing: /usr/local/include/mtf/ThirdParty/DSST/sse.hpp
-- Installing: /usr/local/include/mtf/ThirdParty/DSST/DSST.h
-- Installing: /usr/local/include/mtf/ThirdParty/DSST/HOG.h
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/mtf
-- Up-to-date: /usr/local/include/mtf/ThirdParty
-- Installing: /usr/local/include/mtf/ThirdParty/KCF
-- Installing: /usr/local/include/mtf/ThirdParty/KCF/KCF.h
-- Installing: /usr/local/include/mtf/ThirdParty/KCF/defines.h
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/mtf
-- Up-to-date: /usr/local/include/mtf/ThirdParty
-- Installing: /usr/local/include/mtf/ThirdParty/CMT
-- Installing: /usr/local/include/mtf/ThirdParty/CMT/Matcher.h
-- Installing: /usr/local/include/mtf/ThirdParty/CMT/getopt
-- Installing: /usr/local/include/mtf/ThirdParty/CMT/getopt/getopt.h
-- Installing: /usr/local/include/mtf/ThirdParty/CMT/Consensus.h
-- Installing: /usr/local/include/mtf/ThirdParty/CMT/Fusion.h
-- Installing: /usr/local/include/mtf/ThirdParty/CMT/fastcluster
-- Installing: /usr/local/include/mtf/ThirdParty/CMT/fastcluster/fastcluster.h
-- Installing: /usr/local/include/mtf/ThirdParty/CMT/CMT.h
-- Installing: /usr/local/include/mtf/ThirdParty/CMT/gui.h
-- Installing: /usr/local/include/mtf/ThirdParty/CMT/common.h
-- Installing: /usr/local/include/mtf/ThirdParty/CMT/Tracker.h
-- Installing: /usr/local/include/mtf/ThirdParty/CMT/logging
-- Installing: /usr/local/include/mtf/ThirdParty/CMT/logging/log.h
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/mtf
-- Up-to-date: /usr/local/include/mtf/ThirdParty
-- Installing: /usr/local/include/mtf/ThirdParty/RCT
-- Installing: /usr/local/include/mtf/ThirdParty/RCT/RCT.h
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/mtf
-- Up-to-date: /usr/local/include/mtf/ThirdParty
-- Installing: /usr/local/include/mtf/ThirdParty/TLD
-- Installing: /usr/local/include/mtf/ThirdParty/TLD/mftracker
-- Installing: /usr/local/include/mtf/ThirdParty/TLD/mftracker/BB.h
-- Installing: /usr/local/include/mtf/ThirdParty/TLD/mftracker/Median.h
-- Installing: /usr/local/include/mtf/ThirdParty/TLD/mftracker/BBPredict.h
-- Installing: /usr/local/include/mtf/ThirdParty/TLD/mftracker/FBTrack.h
-- Installing: /usr/local/include/mtf/ThirdParty/TLD/mftracker/Lk.h
-- Installing: /usr/local/include/mtf/ThirdParty/TLD/TLD.h
-- Installing: /usr/local/include/mtf/ThirdParty/TLD/VarianceFilter.h
-- Installing: /usr/local/include/mtf/ThirdParty/TLD/Clustering.h
-- Installing: /usr/local/include/mtf/ThirdParty/TLD/NNClassifier.h
-- Installing: /usr/local/include/mtf/ThirdParty/TLD/IntegralImage.h
-- Installing: /usr/local/include/mtf/ThirdParty/TLD/NormalizedPatch.h
-- Installing: /usr/local/include/mtf/ThirdParty/TLD/DetectionResult.h
-- Installing: /usr/local/include/mtf/ThirdParty/TLD/TLDUtil.h
-- Installing: /usr/local/include/mtf/ThirdParty/TLD/MedianFlowTracker.h
-- Installing: /usr/local/include/mtf/ThirdParty/TLD/ForegroundDetector.h
-- Installing: /usr/local/include/mtf/ThirdParty/TLD/DetectorCascade.h
-- Installing: /usr/local/include/mtf/ThirdParty/TLD/EnsembleClassifier.h
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/mtf
-- Up-to-date: /usr/local/include/mtf/ThirdParty
-- Installing: /usr/local/include/mtf/ThirdParty/Struck
-- Installing: /usr/local/include/mtf/ThirdParty/Struck/Config.h
-- Installing: /usr/local/include/mtf/ThirdParty/Struck/HaarFeatures.h
-- Installing: /usr/local/include/mtf/ThirdParty/Struck/HistogramFeatures.h
-- Installing: /usr/local/include/mtf/ThirdParty/Struck/MultiFeatures.h
-- Installing: /usr/local/include/mtf/ThirdParty/Struck/Features.h
-- Installing: /usr/local/include/mtf/ThirdParty/Struck/Rect.h
-- Installing: /usr/local/include/mtf/ThirdParty/Struck/Sample.h
-- Installing: /usr/local/include/mtf/ThirdParty/Struck/Tracker.h
-- Installing: /usr/local/include/mtf/ThirdParty/Struck/HaarFeature.h
-- Installing: /usr/local/include/mtf/ThirdParty/Struck/Sampler.h
-- Installing: /usr/local/include/mtf/ThirdParty/Struck/LaRank.h
-- Installing: /usr/local/include/mtf/ThirdParty/Struck/ImageRep.h
-- Installing: /usr/local/include/mtf/ThirdParty/Struck/Kernels.h
-- Installing: /usr/local/include/mtf/ThirdParty/Struck/RawFeatures.h
-- Installing: /usr/local/include/mtf/ThirdParty/Struck/GraphUtils
-- Installing: /usr/local/include/mtf/ThirdParty/Struck/GraphUtils/GraphUtils.h
-- Installing: /usr/local/include/mtf/ThirdParty/Struck/Struck.h
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/mtf
-- Up-to-date: /usr/local/include/mtf/ThirdParty
-- Installing: /usr/local/include/mtf/ThirdParty/MIL
-- Installing: /usr/local/include/mtf/ThirdParty/MIL/cv_onlineboosting.h
-- Installing: /usr/local/include/mtf/ThirdParty/MIL/cv_onlinemil.h
-- Installing: /usr/local/include/mtf/ThirdParty/MIL/MIL.h
-- Installing: /usr/local/include/mtf/ThirdParty/MIL/object_tracker.h
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/mtf
-- Up-to-date: /usr/local/include/mtf/ThirdParty
-- Installing: /usr/local/include/mtf/ThirdParty/FRG
-- Installing: /usr/local/include/mtf/ThirdParty/FRG/Fragments_Tracker.hpp
-- Installing: /usr/local/include/mtf/ThirdParty/FRG/emd.hpp
-- Installing: /usr/local/include/mtf/ThirdParty/FRG/vot.hpp
-- Installing: /usr/local/include/mtf/ThirdParty/FRG/FRG.h
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/mtf
-- Up-to-date: /usr/local/include/mtf/ThirdParty
-- Installing: /usr/local/include/mtf/ThirdParty/ViSP
-- Installing: /usr/local/include/mtf/ThirdParty/ViSP/ViSP.h
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/mtf
-- Installing: /usr/local/include/mtf/Macros
-- Installing: /usr/local/include/mtf/Macros/common.h
-- Installing: /usr/local/include/mtf/Macros/register.h
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/mtf
-- Installing: /usr/local/include/mtf/Config
-- Installing: /usr/local/include/mtf/Config/datasets.h
-- Installing: /usr/local/include/mtf/Config/parameters.h
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/mtf
-- Installing: /usr/local/include/mtf/Utilities
-- Installing: /usr/local/include/mtf/Utilities/objUtils.h
-- Installing: /usr/local/include/mtf/Utilities/excpUtils.h
-- Installing: /usr/local/include/mtf/Utilities/graphUtils.h
-- Installing: /usr/local/include/mtf/Utilities/warpUtils.h
-- Installing: /usr/local/include/mtf/Utilities/netUtils.h
-- Installing: /usr/local/include/mtf/Utilities/inputUtils.h
-- Installing: /usr/local/include/mtf/Utilities/miscUtils.h
-- Installing: /usr/local/include/mtf/Utilities/histUtils.h
-- Installing: /usr/local/include/mtf/Utilities/spiUtils.h
-- Installing: /usr/local/include/mtf/Utilities/imgUtils.h
-- Installing: /usr/local/include/mtf/Utilities/preprocUtils.h
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/mtf
-- Installing: /usr/local/include/mtf/AM
-- Installing: /usr/local/include/mtf/AM/AMParams.h
-- Installing: /usr/local/include/mtf/AM/NCC.h
-- Installing: /usr/local/include/mtf/AM/SPSS.h
-- Installing: /usr/local/include/mtf/AM/IlluminationModel.h
-- Installing: /usr/local/include/mtf/AM/SSIM.h
-- Installing: /usr/local/include/mtf/AM/ZNCC.h
-- Installing: /usr/local/include/mtf/AM/MCPCA.h
-- Installing: /usr/local/include/mtf/AM/MI.h
-- Installing: /usr/local/include/mtf/AM/DFM.h
-- Installing: /usr/local/include/mtf/AM/SSD.h
-- Installing: /usr/local/include/mtf/AM/MCSPSS.h
-- Installing: /usr/local/include/mtf/AM/MCSCV.h
-- Installing: /usr/local/include/mtf/AM/GB.h
-- Installing: /usr/local/include/mtf/AM/CCRE.h
-- Installing: /usr/local/include/mtf/AM/LRSCV.h
-- Installing: /usr/local/include/mtf/AM/AppearanceModel.h
-- Installing: /usr/local/include/mtf/AM/MCZNCC.h
-- Installing: /usr/local/include/mtf/AM/MCSSD.h
-- Installing: /usr/local/include/mtf/AM/MCSAD.h
-- Installing: /usr/local/include/mtf/AM/NSSD.h
-- Installing: /usr/local/include/mtf/AM/MCSSIM.h
-- Installing: /usr/local/include/mtf/AM/PCA.h
-- Installing: /usr/local/include/mtf/AM/MCMI.h
-- Installing: /usr/local/include/mtf/AM/MCRSCV.h
-- Installing: /usr/local/include/mtf/AM/LSCV.h
-- Installing: /usr/local/include/mtf/AM/LKLD.h
-- Installing: /usr/local/include/mtf/AM/MCCCRE.h
-- Installing: /usr/local/include/mtf/AM/MCRIU.h
-- Installing: /usr/local/include/mtf/AM/RBF.h
-- Installing: /usr/local/include/mtf/AM/SumOfAMs.h
-- Installing: /usr/local/include/mtf/AM/SCV.h
-- Installing: /usr/local/include/mtf/AM/MCNCC.h
-- Installing: /usr/local/include/mtf/AM/SSDBase.h
-- Installing: /usr/local/include/mtf/AM/PGB.h
-- Installing: /usr/local/include/mtf/AM/MCLSCV.h
-- Installing: /usr/local/include/mtf/AM/RSCV.h
-- Installing: /usr/local/include/mtf/AM/KLD.h
-- Installing: /usr/local/include/mtf/AM/SAD.h
-- Installing: /usr/local/include/mtf/AM/ImageBase.h
-- Installing: /usr/local/include/mtf/AM/NGF.h
-- Installing: /usr/local/include/mtf/AM/RIU.h
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/mtf
-- Installing: /usr/local/include/mtf/SSM
-- Installing: /usr/local/include/mtf/SSM/SSMEstimatorParams.h
-- Installing: /usr/local/include/mtf/SSM/HomographyEstimator.h
-- Installing: /usr/local/include/mtf/SSM/LieAffine.h
-- Installing: /usr/local/include/mtf/SSM/SSMEstimator.h
-- Installing: /usr/local/include/mtf/SSM/LieHomography.h
-- Installing: /usr/local/include/mtf/SSM/StateSpaceModel.h
-- Installing: /usr/local/include/mtf/SSM/AffineEstimator.h
-- Installing: /usr/local/include/mtf/SSM/Affine.h
-- Installing: /usr/local/include/mtf/SSM/Isometry.h
-- Installing: /usr/local/include/mtf/SSM/CBH.h
-- Installing: /usr/local/include/mtf/SSM/Spline.h
-- Installing: /usr/local/include/mtf/SSM/TPS.h
-- Installing: /usr/local/include/mtf/SSM/SL3.h
-- Installing: /usr/local/include/mtf/SSM/ASRT.h
-- Installing: /usr/local/include/mtf/SSM/Translation.h
-- Installing: /usr/local/include/mtf/SSM/LieIsometry.h
-- Installing: /usr/local/include/mtf/SSM/ProjectiveBase.h
-- Installing: /usr/local/include/mtf/SSM/Similitude.h
-- Installing: /usr/local/include/mtf/SSM/IST.h
-- Installing: /usr/local/include/mtf/SSM/Homography.h
-- Installing: /usr/local/include/mtf/SSM/AST.h
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/mtf
-- Installing: /usr/local/include/mtf/SM
-- Installing: /usr/local/include/mtf/SM/PF.h
-- Installing: /usr/local/include/mtf/SM/CompositeSM.h
-- Installing: /usr/local/include/mtf/SM/opencv2
-- Installing: /usr/local/include/mtf/SM/opencv2/core
-- Installing: /usr/local/include/mtf/SM/opencv2/core/internal.hpp
-- Installing: /usr/local/include/mtf/SM/FALK.h
-- Installing: /usr/local/include/mtf/SM/NN.h
-- Installing: /usr/local/include/mtf/SM/SearchMethod.h
-- Installing: /usr/local/include/mtf/SM/CascadeParams.h
-- Installing: /usr/local/include/mtf/SM/HESM.h
-- Installing: /usr/local/include/mtf/SM/CascadeSM.h
-- Installing: /usr/local/include/mtf/SM/ICLKParams.h
-- Installing: /usr/local/include/mtf/SM/RegNetParams.h
-- Installing: /usr/local/include/mtf/SM/ESMParams.h
-- Installing: /usr/local/include/mtf/SM/GridTrackerFlowParams.h
-- Installing: /usr/local/include/mtf/SM/GridBase.h
-- Installing: /usr/local/include/mtf/SM/PyramidalParams.h
-- Installing: /usr/local/include/mtf/SM/GridTrackerCV.h
-- Installing: /usr/local/include/mtf/SM/RKLTParams.h
-- Installing: /usr/local/include/mtf/SM/IALK.h
-- Installing: /usr/local/include/mtf/SM/GridTracker.h
-- Installing: /usr/local/include/mtf/SM/PyramidalSM.h
-- Installing: /usr/local/include/mtf/SM/FLANNCVParams.h
-- Installing: /usr/local/include/mtf/SM/NT
-- Installing: /usr/local/include/mtf/SM/NT/PF.h
-- Installing: /usr/local/include/mtf/SM/NT/FALK.h
-- Installing: /usr/local/include/mtf/SM/NT/NN.h
-- Installing: /usr/local/include/mtf/SM/NT/SearchMethod.h
-- Installing: /usr/local/include/mtf/SM/NT/AESM.h
-- Installing: /usr/local/include/mtf/SM/NT/RegNet.h
-- Installing: /usr/local/include/mtf/SM/NT/IALK.h
-- Installing: /usr/local/include/mtf/SM/NT/ESM.h
-- Installing: /usr/local/include/mtf/SM/NT/GNN.h
-- Installing: /usr/local/include/mtf/SM/NT/GridTrackerFlow.h
-- Installing: /usr/local/include/mtf/SM/NT/FCSD.h
-- Installing: /usr/local/include/mtf/SM/NT/RKLT.h
-- Installing: /usr/local/include/mtf/SM/NT/ICLK.h
-- Installing: /usr/local/include/mtf/SM/NT/FCLK.h
-- Installing: /usr/local/include/mtf/SM/NNParams.h
-- Installing: /usr/local/include/mtf/SM/LineTracker.h
-- Installing: /usr/local/include/mtf/SM/FCLKParams.h
-- Installing: /usr/local/include/mtf/SM/PFParams.h
-- Installing: /usr/local/include/mtf/SM/FLANNParams.h
-- Installing: /usr/local/include/mtf/SM/ESM.h
-- Installing: /usr/local/include/mtf/SM/FeatureTracker.h
-- Installing: /usr/local/include/mtf/SM/GNN.h
-- Installing: /usr/local/include/mtf/SM/PyramidalTracker.h
-- Installing: /usr/local/include/mtf/SM/CompositeBase.h
-- Installing: /usr/local/include/mtf/SM/HACLK.h
-- Installing: /usr/local/include/mtf/SM/GridTrackerFlow.h
-- Installing: /usr/local/include/mtf/SM/GNNParams.h
-- Installing: /usr/local/include/mtf/SM/FGNN.h
-- Installing: /usr/local/include/mtf/SM/RKLT.h
-- Installing: /usr/local/include/mtf/SM/FESMBase.h
-- Installing: /usr/local/include/mtf/SM/ParallelSM.h
-- Installing: /usr/local/include/mtf/SM/CascadeTracker.h
-- Installing: /usr/local/include/mtf/SM/ESMH.h
-- Installing: /usr/local/include/mtf/SM/IALK2.h
-- Installing: /usr/local/include/mtf/SM/FALKParams.h
-- Installing: /usr/local/include/mtf/SM/ICLK.h
-- Installing: /usr/local/include/mtf/SM/FESM.h
-- Installing: /usr/local/include/mtf/SM/FCLK.h
-- Installing: /usr/local/include/mtf/SM/FeatureBase.h
-- Installing: /usr/local/include/mtf/SM/ParallelTracker.h
-- Installing: /usr/local/include/mtf/SM/IALKParams.h
-- Installing: /usr/local/include/mtf/SM/ParallelParams.h
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/mtf
-- Installing: /usr/local/include/mtf/Test
-- Installing: /usr/local/include/mtf/Test/Diagnostics.h
-- Installing: /usr/local/include/mtf/Test/DiagBase.h
-- Installing: /usr/local/lib/libcmt.so
-- Set runtime path of "/usr/local/lib/libcmt.so" to ""
-- Installing: /usr/local/lib/libopentld.so
-- Set runtime path of "/usr/local/lib/libopentld.so" to ""
-- Installing: /usr/local/lib/libcvblobs.so
-- Installing: /usr/local/lib/libstruck.so
-- Set runtime path of "/usr/local/lib/libstruck.so" to ""
-- Installing: /usr/local/lib/libmil.so
-- Set runtime path of "/usr/local/lib/libmil.so" to ""
-- Installing: /usr/local/lib/libfrg.so
-- Set runtime path of "/usr/local/lib/libfrg.so" to ""

**Comment by abhineet123** [comment]
You need to add the library installation folder  `/usr/local/lib` to the `LD_LIBRARY_PATH` and `LIBRARY_PATH` environment variables as it says in the `Compile/Runtime Notes` section of the ReadMe.

**Comment by abhineet123** [comment]
BTW `testMTF `is not like a Hello World program at all. It is a complex diagnostic tool I created to help me debug the modules. It outputs a bunch of binary data files that need to be read by Matlab scripts in my [Python Tracking Framework](https://github.com/abhineet123/PTF) to produce plots that show whether the modules are working as expected.

Use `runMTF `to perform tracking. Some sample config files are provided on the github page that can help you get started.

**Comment by kneczaj** [comment]
Thanks, sorry for not reading patiently the docs, but for now all issues were just bugs :P. Obviously your solution works!

**Comment by kneczaj** [comment]
you can close or use my suggestion if you have time :)
