### ISSUE TITLE
Error Building MTF

### ISSUE THREAD

**Issue by imtihan** [abhineet123/MTF#13]
Hi, I seem to be getting this error when I try to install MTF but I can't seem to figure out what may be causing this.

/usr/bin/ld: cannot find -lQt5::Core
/usr/bin/ld: cannot find -lQt5::Gui
/usr/bin/ld: cannot find -lQt5::Widgets
/usr/bin/ld: cannot find -lQt5::Test
/usr/bin/ld: cannot find -lQt5::Concurrent
/usr/bin/ld: cannot find -lQt5::OpenGL
collect2: error: ld returned 1 exit status
ThirdParty/FRG/CMakeFiles/frg.dir/build.make:211: recipe for target 'ThirdParty/FRG/libfrg.so' failed
make[2]: *** [ThirdParty/FRG/libfrg.so] Error 1
CMakeFiles/Makefile2:1863: recipe for target 'ThirdParty/FRG/CMakeFiles/frg.dir/all' failed
make[1]: *** [ThirdParty/FRG/CMakeFiles/frg.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by abhineet123** [comment]
Please provide more information about the build system including OS and OpenCV version.

**Comment by abhineet123** [comment]
This may have been caused by an unnecessary VOT dependency in FRG tracker that has now been removed. 
Please try compiling again with the latest code and let me know if this issue persists.

**Comment by imtihan** [comment]
That did not resolve my issue. I think it was related to the openCV installation I had, reinstalling openCV 3 fixed that specific error. Thanks!
