### ISSUE TITLE
[HELP wanted]Polygon bounding box tracker recommendation

### ISSUE THREAD

**Issue by MiaoDX** [abhineet123/MTF#15]
HELP wanted, not issue for this project.

Hi,

Thanks for this nice library again, it helps a lot for my projects. The most interesting part is that some of your trackers can track non-rectangle bbox, like a Polygon. I am wondering is there some moderate/smaller standalone trackers does the same thing? I somewhat need this particular feature in my recent project, but most of out-of-the-box ones (like trackers in OpenCV and dlib) are using rectangle (as default?), and your project is a little too big for a submodule of one project which meant to be small itself.

Looking for your relay.

--MiaoDX

**Comment by abhineet123** [comment]
The only thing I am aware of is this boundary tracking system that one of my lab colleagues created:
https://github.com/NathanUA/SalientClosedBoundaryTracking

**Comment by MiaoDX** [comment]
Yeah, 

thanks for that, it seems enough (I will try it today). However, maybe I did not describe clear enough, in fact, a tracker track a non-rectangle **4-edge** polygon is enough for me, so is there something else for this?

**Comment by abhineet123** [comment]
ViSP has a [template tracking module](https://visp.inria.fr/template-tracking/) that allows selecting polygons through two triangles.

**Comment by MiaoDX** [comment]
Okay, I will digest into these, thanks a lot! And I will close this issue now.

**Comment by abhineet123** [comment]
There is also an 8 DOF particle filter implementation in C++ that allows arbitrary polygons:
https://cv.snu.ac.kr/jhkwon/PAMI14_tracking/index.htm
