### ISSUE TITLE
Error when building MTF in Visual Studio

### ISSUE THREAD

**Issue by tgyaoh** [abhineet123/MTF#16]
Hi,

After I open MTF.sln in VS and run Build->Build Solution for a moment, more than 100 errors have occurred and the compilation failed. 

These errors are shown below:

![tim 20180328213951](https://user-images.githubusercontent.com/18618289/38036027-59382b62-32d8-11e8-984e-a13805a05ec0.png)
![tim 20180328223535](https://user-images.githubusercontent.com/18618289/38036036-5f707066-32d8-11e8-88f7-3262cb460d87.png)
![tim 20180328223612](https://user-images.githubusercontent.com/18618289/38036056-6fd7977c-32d8-11e8-857e-91a24fe5353b.png)
![tim 20180328223641](https://user-images.githubusercontent.com/18618289/38036085-7f923eb0-32d8-11e8-9f92-40de509d71f9.png)

**Comment by abhineet123** [comment]
Can you post the errors in English ?
From what I can tell, this seems like an Eigen related error. Please update Eigen to 3.2.10 or newer and let me know if this still persists.

**Comment by tgyaoh** [comment]
Thanks for your solution!
But the Eigen version I installed is 3.3.1, which is newer than 3.2.10.  

And I change the language to English, the errors are shown below，

>C:\Users\yaohan\Desktop\MTF-master\SM\include\mtf/SM/NT/GNN.h(77): error C2062: Unexpected type "int"
2>C:\Users\yaohan\Desktop\MTF-master\SM\include\mtf/SM/NT/GNN.h(77): error C2334: Unexpected flag in front of ":"; skips over the apparent body of the function
2>C:\Users\yaohan\Desktop\MTF-master\SM\include\mtf/SM/NT/GNN.h(83): error C2143: Syntax error: Missing ")" (in front of ";")
2>C:\Users\yaohan\Desktop\MTF-master\SM\include\mtf/SM/NT/GNN.h(83): error C2059: Syntax error: ")"
2>C:\Users\yaohan\Desktop\MTF-master\SM\include\mtf/SM/NT/GNN.h(83): error C2238: Unexpected token is located before ";"
2>C:\Users\yaohan\Desktop\MTF-master\SM\include\mtf/SM/NT/GNN.h(85): error C2143: Syntax error: Missing ";" (in front of "}")
2>C:\Users\yaohan\Desktop\MTF-master\SM\include\mtf/SM/NT/NN.h(10): error C2504: "SearchMethod": Undefined base class
2>C:\Users\yaohan\Desktop\MTF-master\SM\include\mtf/SM/NT/NN.h(15): error C3083: "gnn": The symbol on the left of "::" must be a Types
2>C:\Users\yaohan\Desktop\MTF-master\SM\include\mtf/SM/NT/NN.h(15): error C2039: "GNN": not "mtf::mtf::nt" member
2> C:\Users\yaohan\Desktop\MTF-master\SM\include\mtf/SM/NT/NN.h(9): note: See the statement "mtf::mtf::nt"
2>C:\Users\yaohan\Desktop\MTF-master\SM\include\mtf/SM/NT/NN.h(15): error C3646: "GNN": Unknown Rewrite specifier
2>C:\Users\yaohan\Desktop\MTF-master\SM\include\mtf/SM/NT/NN.h(15): error C4430: Missing type specifier - Assume int. Note: C++ does not support the default int
2>C:\Users\yaohan\Desktop\MTF-master\SM\include\mtf/SM/NT/NN.h(18): error C2061: Syntax error: Identifier "AM"
2>C:\Users\yaohan\Desktop\MTF-master\SM\include\mtf/SM/NT/NN.h(21): error C3668: "mtf::mtf::nt::NN::initialize" : Method That Contains Override Specifier "Override" Does Not Overwrite Any Base Class Method
2>C:\Users\yaohan\Desktop\MTF-master\SM\include\mtf/SM/NT/NN.h(22): error C3668: "mtf::mtf::nt::NN::update" : Method That Contains Override Specifier "Override" Does Not Overwrite Any Base Class Method

2>J:\opencv\build\include\opencv2/highgui/highgui.hpp(194): error C2086: "int mtf::cv::Mat": redefine
2> J:\opencv\build\include\opencv2/highgui/highgui.hpp(190): note: See the statement "mtf::cv::Mat"
2>J:\opencv\build\include\opencv2/highgui/highgui.hpp(194): error C2146: Syntax error: Missing ";" (in front of identifier "imdecode")
2>J:\opencv\build\include\opencv2/highgui/highgui.hpp(195): error C2061: Syntax error: Identifier "InputArray"
2>J:\opencv\build\include\opencv2/highgui/highgui.hpp(201): error C2988: Unrecognized template declaration/definition
2>J:\opencv\build\include\opencv2/highgui/highgui.hpp(201): error C2143: Syntax error: Missing ";" (before "<")
2>J:\opencv\build\include\opencv2/highgui/highgui.hpp(201): error C2182: "Ptr": Illegal use of "void" type
2>J:\opencv\build\include\opencv2/highgui/highgui.hpp(201): error C2059: Syntax error: "<"
2>J:\opencv\build\include\opencv2/highgui/highgui.hpp(201): error C2039: "delete_obj": Not a member of "`global namespace'"
2>J:\opencv\build\include\opencv2/highgui/highgui.hpp(202): error C2039: "delete_obj": Not a member of "`global namespace'"
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(8): error C2065: "AM": Undeclared identifier
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(8): error C2146: Syntax error: ")" is missing (in front of identifier "_am")
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(9): error C2065: "_am": undeclared identifier
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(9): error C2065: "_ssm": Undeclared identifier
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(9): error C4430: Missing type specifier - Assume int. Note: C++ does not support the default int
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(9): error C2440: "Initialize": Cannot convert from "initializer list" to "int"
2> C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(9): note: The initializer contains too many elements
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(10): error C2065: "nn_params": Undeclared identifier
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(10): error C4430: Missing type specifier - Assume int. Note: C++ does not support the default int
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(11): error C4430: Missing type specifier - Assume int. Note: C++ does not support the default int
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(11): error C2448: "mtf::mtf::nt::dataset_loaded": Function style initial value setting Item like function definition
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(57): error C4430: Missing type specifier - Assume int. Note: C++ does not support the default int
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(57): error C2751: "mtf::cv::Mat": Unable to qualify function parameter name
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(57): error C2988: Unrecognized template declaration/definition
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(57): error C2143: Syntax error: Missing "," (before "&")
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(57): error C2511: "void mtf::mtf::nt::NN::initialize(const int) : "Mtf::mtf::nt::NN" did not find an overloaded member function
2> C:\Users\yaohan\Desktop\MTF-master\SM\include\mtf/SM/NT/NN.h(10): note: See the statement "mtf::mtf::nt::NN"
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(60): error C2065: "am": undeclared identifier
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(60): error C2227: The left side of "->clearInitStatus" must point to class/structure/union/generic type
2> C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(60): note: The type is "unknown-type"
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(61): error C2065: "ssm": undeclared identifier
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(61): error C2227: The left side of "->clearInitStatus" must point to class/structure/union/generic type
2> C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(61): note: The type is "unknown-type"
2>C:\Users\yaohan\Desktop\MTF-master\SM\src\NT\NN.cc(63): error C2065: "ssm": Undeclared identifier

6>c:\users\yaohan\desktop\mtf-master\am\include\mtf\am\SSDBase.h(132): error C2143: Syntax error: Missing ";" (in front of "<")
6>c:\users\yaohan\desktop\mtf-master\am\include\mtf\am\SSDBase.h(132): error C4430: Missing type specifier - Assume int. Note: C++ does not support the default int
6>c:\users\yaohan\desktop\mtf-master\am\include\mtf\am\SSDBase.h(132): error C2238: Unexpected token is before ";"
6>c:\users\yaohan\desktop\mtf-master\am\include\mtf\am\SSDBase.h(133): error C2653: "SampleDistT": not a class or namespace name
6>c:\users\yaohan\desktop\mtf-master\am\include\mtf\am\SSDBase.h(133): error C3646: "DistParamT": Unknown rewrite specifier
6>c:\users\yaohan\desktop\mtf-master\am\include\mtf\am\SSDBase.h(133): error C4430: Missing type specifier - Assume int. Note: C++ does not support the default int
6>c:\users\yaohan\desktop\mtf-master\am\include\mtf\am\SSDBase.h(136): error C2065: "SampleDistT": undeclared identifier
6>c:\users\yaohan\desktop\mtf-master\am\include\mtf\am\SSDBase.h(136): error C2923: "std::vector": For parameter "_Ty", "SampleDistT" is not Valid template type variables
6>j:\mtf_dependencies\eigen3.3.1\include\eigen3\eigen\src/SparseCore/SparseUtil.h(78): error C2988: Unrecognized template declaration/definition
6>j:\mtf_dependencies\eigen3.3.1\include\eigen3\eigen\src/SparseCore/SparseUtil.h(78): error C2143: Syntax error: Missing ";" (in front of "<")
6>j:\mtf_dependencies\eigen3.3.1\include\eigen3\eigen\src/SparseCore/SparseUtil.h(78): error C2059: Syntax error: "<"
6>j:\mtf_dependencies\eigen3.3.1\include\eigen3\eigen\src/SparseCore/SparseUtil.h(79): error C2065: "T": Undeclared identifier
6>j:\mtf_dependencies\eigen3.3.1\include\eigen3\eigen\src/SparseCore/SparseUtil.h(79): error C2065: "traits": undeclared identifier
6>j:\mtf_dependencies\eigen3.3.1\include\eigen3\eigen\src/SparseCore/SparseUtil.h(79): error C2976: "mtf::Eigen::internal::sparse_eval": Template Too few parameters
6> j:\mtf_dependencies\eigen3.3.1\include\eigen3\eigen\src/SparseCore/SparseUtil.h(76): note: See the statement "mtf::Eigen::internal::sparse_eval"
6>j:\mtf_dependencies\eigen3.3.1\include\eigen3\eigen\src/SparseCore/SparseUtil.h(79): error C2955: "mtf::Eigen::internal::sparse_eval": Using a class template requires template parameters Lists
6> j:\mtf_dependencies\eigen3.3.1\include\eigen3\eigen\src/SparseCore/SparseUtil.h(76): note: See the statement "mtf::Eigen::internal::sparse_eval"
6>j:\mtf_dependencies\eigen3.3.1\include\eigen3\eigen\src/SparseCore/SparseUtil.h(79): error C2027: Undefined type "mtf::Eigen::internal::sparse_eval" is used
6> j:\mtf_dependencies\eigen3.3.1\include\eigen3\eigen\src/SparseCore/SparseUtil.h(76): note: See the statement "mtf::Eigen::internal::sparse_eval"
6>j:\mtf_dependencies\eigen3.3.1\include\eigen3\eigen\src/SparseCore/SparseUtil.h(79): error C4430: Missing type specifier - Assume int. Note: C++ does not support the default int
6>j:\mtf_dependencies\eigen3.3.1\include\eigen3\eigen\src/SparseCore/SparseUtil.h(79): error C2143: Syntax error: Missing ";" (in front of "<")
6>j:\mtf_dependencies\eigen3.3.1\include\eigen3\eigen\src/SparseCore/SparseUtil.h(79): error C2039: "ColsAtCompileTime": Not a member of "`global namespace'"
6>j:\mtf_dependencies\eigen3.3.1\include\eigen3\eigen\src/SparseCore/SparseUtil.h(79): error C2039: "Flags": Not a member of "`global namespace'"
6>j:\mtf_dependencies\eigen3.3.1\include\eigen3\eigen\src/SparseCore/SparseUtil.h(80): error C2143: Syntax error: Missing ";" (before "{")

**Comment by abhineet123** [comment]
It seems that there were some `windows.h` includes within thirdparty modules that were conflicting with some pre-included headers in VS. Also, there were some #defines I had added for intellisense and forrgotten to remove.
Both issues have been fixed now and it is compiling fine on my system.
Please try compiling again and let me know if any issues still remain.

**Comment by tgyaoh** [comment]
Yeah, when I recompile, there is no error. 
Thanks a lot !! And I will close this issue.
