### ISSUE TITLE
MTF compilation on Ubuntu 16.10/opencv 3.2

### ISSUE THREAD

**Issue by kneczaj** [abhineet123/MTF#2]
Hello,

I am trying to compile MTF, as it would be very usefull for my thesis.

My environment is Ubuntu 16.10 on VirtualBox with open cv 3.2 compiled from sources together with opencv_contrib. So very briefly that's the error:

> kamil@kamil-VirtualBox ~/dev/MTF/build_nn $ make
Makefile:240: warning: overriding recipe for target 'all'
Makefile:127: warning: ignoring old recipe for target 'all'
[ 93%] Built target mtf_test
[ 87%] Built target mtf
[ 88%] Built target generateSyntheticSeq
[ 90%] Built target mtf_test
[ 91%] Built target testMTF
[ 92%] Linking CXX executable trackMarkers
CMakeFiles/trackMarkers.dir/Examples/cpp/trackMarkers.cc.o: In function `mtf::TrackerBase* mtf::getTracker<mtf::MCPCA, mtf::Spline>(char const*, mtf::MCPCA::ParamType const*, mtf::Spline::ParamType const*)':
trackMarkers.cc:(.text._ZN3mtf10getTrackerINS_5MCPCAENS_6SplineEEEPNS_11TrackerBaseEPKcPKNT_9ParamTypeEPKNT0_9ParamTypeE[_ZN3mtf10getTrackerINS_5MCPCAENS_6SplineEEEPNS_11TrackerBaseEPKcPKNT_9ParamTypeEPKNT0_9ParamTypeE]+0x2397): undefined reference to `mtf::FeatureTrackerParams::FeatureTrackerParams(int, int, int, int, bool, mtf::FeatureTrackerParams::DetectorType, mtf::FeatureTrackerParams::DescriptorType, bool, int, double, bool, bool, double, int, bool, bool, bool, bool)'
trackMarkers.cc:(.text._ZN3mtf10getTrackerINS_5MCPCAENS_6SplineEEEPNS_11TrackerBaseEPKcPKNT_9ParamTypeEPKNT0_9ParamTypeE[_ZN3mtf10getTrackerINS_5MCPCAENS_6SplineEEEPNS_11TrackerBaseEPKcPKNT_9ParamTypeEPKNT0_9ParamTypeE]+0x23d5): undefined reference to `mtf::SIFTParams::SIFTParams(int, int, double, double, double)'
trackMarkers.cc:(.text._ZN3mtf10getTrackerINS_5MCPCAENS_6SplineEEEPNS_11TrackerBaseEPKcPKNT_9ParamTypeEPKNT0_9ParamTypeE[_ZN3mtf10getTrackerINS_5MCPCAENS_6SplineEEEPNS_11TrackerBaseEPKcPKNT_9ParamTypeEPKNT0_9ParamTypeE]+0x2446): undefined reference to `mtf::FeatureTracker<mtf::Spline>::FeatureTracker(mtf::FeatureTrackerParams const*, mtf::SIFTParams const*, mtf::FLANNCVParams const*, mtf::SSMEstimatorParams const*, mtf::SplineParams const*)'
CMakeFiles/trackMarkers.dir/Examples/cpp/trackMarkers.cc.o: In function `mtf::TrackerBase* mtf::getTracker<mtf::SSD, mtf::LieHomography>(char const*, mtf::SSD::ParamType const*, mtf::LieHomography::ParamType const*)':
trackMarkers.cc:(.text._ZN3mtf10getTrackerINS_3SSDENS_13LieHomographyEEEPNS_11TrackerBaseEPKcPKNT_9ParamTypeEPKNT0_9ParamTypeE[_ZN3mtf10getTrackerINS_3SSDENS_13LieHomographyEEEPNS_11TrackerBaseEPKcPKNT_9ParamTypeEPKNT0_9ParamTypeE]+0x2397): undefined reference to `mtf::FeatureTrackerParams::FeatureTrackerParams(int, int, int, int, bool, mtf::FeatureTrackerParams::DetectorType, mtf::FeatureTrackerParams::DescriptorType, bool, int, double, bool, bool, double, int, bool, bool, bool, bool)'

It's briefly because that's only the couple of first lines of the linking errors, which are longer than a 1000 lines together. The mtf.so seems compiled and is in the build directory.

I use cmake, that's the output of `cmake ..`:
>-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   random
--   filesystem
--   system
-- Getting Eigen headers from: /usr/include/eigen3
-- Getting OpenCV headers from: /usr/local/include;/usr/local/include/opencv
-- Using OpenCV libraries: opencv_calib3d;opencv_core;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_aruco;opencv_bgsegm;opencv_bioinspired;opencv_ccalib;opencv_datasets;opencv_dnn;opencv_dpm;opencv_face;opencv_freetype;opencv_fuzzy;opencv_line_descriptor;opencv_optflow;opencv_phase_unwrapping;opencv_plot;opencv_reg;opencv_rgbd;opencv_saliency;opencv_stereo;opencv_structured_light;opencv_surface_matching;opencv_text;opencv_tracking;opencv_xfeatures2d;opencv_ximgproc;opencv_xobjdetect;opencv_xphoto
-- Getting Boost headers from: /usr/include
-- Getting Boost libraries from: /usr/lib/x86_64-linux-gnu
-- Using Boost libraries: /usr/lib/x86_64-linux-gnu/libboost_random.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_system.so
-- DFT disabled
-- PFSL3 disabled
-- Getting ViSP headers from: /usr/local/include;/usr/local/include;/usr/local/include/opencv;/usr/include/libxml2;/usr/include
-- Using ViSP libraries: visp_vs;visp_visual_features;visp_vision;visp_tt_mi;visp_tt;visp_me;visp_mbt;visp_klt;visp_blob;visp_sensor;visp_robot;visp_io;visp_gui;visp_detection;visp_core;visp_ar
-- GOTURN disabled
-- Xvision disabled
-- Enabled third party trackers: DSST/src/DSST;KCF/src/KCF;CMT/src/CMT;RCT/src/RCT;TLD/src/TLD;Struck/src/Struck;MIL/src/MIL;FRG/src/FRG;ViSP/src/ViSP
-- DFM disabled
-- OpenCV nonfree module not found so disabling the feature based grid tracker
-- RegNet disabled
-- FLANN based NN is disabled
-- Incompatible version of Python library found so pyMTF is disabled: 3.5.2+
-- Could NOT find Matlab (missing:  Matlab_INCLUDE_DIRS Matlab_MEX_LIBRARY Matlab_MEX_EXTENSION Matlab_ROOT_DIR MEX_COMPILER MX_LIBRARY) 
-- Matlab not found so mexMTF is disabled
If Matlab is installed but not detected, mexMTF can be compiled by running the command in 'mtf_mex_cmd.txt' at the MATLAB prompt after:
         * removing all semi colons
         * replacing all occurences of the type '-l<full path to library>' with '<full path to library>'
         * replacing all occurences of the type '-l-L<path to library folder>' with '-L<path to library folder>'
-- MTF_COMPILETIME_FLAGS: -std=c++11
-- MTF_RUNTIME_FLAGS: -Wfatal-errors;-Wno-write-strings;-Wno-unused-result;-Wformat=0;-std=c++11;-O3;-msse2
-- MTF_DEFINITIIIONS: NDEBUG;EIGEN_NO_DEBUG;DISABLE_DFT;DISABLE_PFSL3;DISABLE_GOTURN;DISABLE_XVISION;DISABLE_DFM;DISABLE_GRID_FEAT;DISABLE_REGNET;DISABLE_FLANN;DISABLE_HDF5;DISABLE_SPI
-- CMAKE_CXX_FLAGS:  -fopenmp
-- CMAKE_C_FLAGS: 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kamil/dev/MTF/build_nn

There is basically NN set to OFF, and also THIRD_PARTY=off set (I don't see it's included in the above)

Thank's in advance for any clue :)

Is it possible that's an issue with opencv 3?

**Comment by abhineet123** [comment]
This seems to be because of missing features in your OpenCV installation. Please rebuild cmake after setting WITH_FEAT to OFF in cmake options or in SM/SM.cmake (line 4).

**Comment by abhineet123** [comment]
Sorry, on examining your cmake output, I realize that the feature module was correctly disabled by itself when the required OpenCV features were not found.
I found a bug in `Examples/Examples.cmake` that was including the `trackMarkers `example executable to the cmake project irrespective of whether or not the feature module was enabled even though it needs this module to work. I have fixed this now. Please pull the latest code, try compiling again and let me know if this problem persists.

**Comment by kneczaj** [comment]
thanks, a lot! I'll check it out in a moment. However building process is quite long so if I start it from scratch it may take an hour or so to let you know if it works.

**Comment by kneczaj** [comment]
now I have a warning at cmake, I think that it's related to your change:

>-- Enabled third party trackers: DSST/src/DSST;KCF/src/KCF;CMT/src/CMT;RCT/src/RCT;TLD/src/TLD;Struck/src/Struck;MIL/src/MIL;FRG/src/FRG;ViSP/src/ViSP
-- DFM disabled
-- Feature based grid tracker disabled
CMake Warning (dev) at SM/SM.cmake:37 (set):
  Cannot set "FEAT_ENABLED": current scope has no parent.
Call Stack (most recent call first):
  CMakeLists.txt:98 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
-- RegNet disabled
-- FLANN based NN is disabled
-- PYTHON_INCLUDE_DIRS: /usr/include/python2.7
-- PYTHON_LIBRARIES: /usr/lib/x86_64-linux-gnu/libpython2.7.so

**Comment by abhineet123** [comment]
It seems I was mistaken about the way variables can be communicated between different modules in cmake. I have tried fixing it by removing the parent scope option. Please pull the latest code and let me know if it works.

**Comment by kneczaj** [comment]
I modified SM.cmake:

```diff --git a/SM/SM.cmake b/SM/SM.cmake
index 390795b..d12d5fd 100644
--- a/SM/SM.cmake
+++ b/SM/SM.cmake
@@ -34,7 +34,7 @@ if(WITH_FEAT)
 else(WITH_FEAT)
        message(STATUS "Feature based grid tracker disabled")
        set(MTF_DEFINITIONS ${MTF_DEFINITIONS} DISABLE_GRID_FEAT)
-       set(FEAT_ENABLED OFF PARENT_SCOPE)
+       set(FEAT_ENABLED OFF)
 endif(WITH_FEAT)
 if(WITH_REGNET)
        set(SEARCH_METHODS_NT ${SEARCH_METHODS_NT} RegNet)
```

seems to get rid of the error, and stops on another ;)

Do you mind if I post more bugs? I really want to compile it, because I need it for my thesis.

**Comment by abhineet123** [comment]
I already made that change but please do feel free to let me know about any other bugs you find.

I tested it on my system and came across another bug - apparently I had changed the name of the pre-processor variable used to keep track of the status of the feature module but had forgotten to make this change in some of the cmake files. This has now been fixed too. 
I also found several minor bugs related to out dated variable names and have fixed them all.

The cmake system is now working fine on my machine but I cannot be sure about other configurations so please pull the latest commit and do let me know if it also works for you.

Very sorry for the trouble and thanks a lot for your help and patience.

BTW you can significantly decrease compilation time by disabling the templated implementations of SMs using `-DWITH_TEMPLATED=OFF` with your cmake command. These provide no functionality not present in their non-templated counterparts.

**Comment by kneczaj** [comment]
Don't worry. When I manage to run it, it may save me much time in writing my thesis :) And I hope we manage to do it together. Anyway looking at your thesis it seems like a peace of a good work!

**Comment by abhineet123** [comment]
Thanks !

**Comment by abhineet123** [comment]
Please let me know if this has been fixed along with #3 and #4 so these can be closed.

**Comment by kneczaj** [comment]
This one is without FLANN, I try with FLANN for now. I'll go back to this one later

**Comment by kneczaj** [comment]
checked - works
