### ISSUE TITLE
The latest version of MTF is not compatible with SimpleTrackingDemo.cc

### ISSUE THREAD

**Issue by tttt0720** [abhineet123/MTF#20]
Hi, @abhineet123 
I'm trying to start with the simplest demo [SimpleTrackingDemo.cc](https://github.com/abhineet123/MTF/blob/master/Examples/cpp/SimpleTrackingDemo.cc) to learn MTF, but I found you have not maintained it so that it can not run successfully with the latest version of MTF.

I fix [mtf::utils::InputCV input('u');](https://github.com/abhineet123/MTF/blob/3e1a66afac7748314141292cac681cf275dce5ed/Examples/cpp/SimpleTrackingDemo.cc#L10) with :
```c++
utils::InputParams* params = new utils::InputParams('u', "", "", "", 1, false);
mtf::utils::InputCV input(params);
```

But there is an error in [tracker.initialize(input.getFrame(), obj_utils.getObj().corners);](https://github.com/abhineet123/MTF/blob/3e1a66afac7748314141292cac681cf275dce5ed/Examples/cpp/SimpleTrackingDemo.cc#L14)

I spent a few hours on this because I don't know MTF well. And I'm worried that there will be some other problems after I solve this by myself. So Could you update [SimpleTrackingDemo.cc](https://github.com/abhineet123/MTF/blob/master/Examples/cpp/SimpleTrackingDemo.cc) and [CompositeTrackingDemo.cc](https://github.com/abhineet123/MTF/blob/master/Examples/cpp/CompositeTrackingDemo.cc) ?

**Comment by abhineet123** [comment]
Sorry for the delay - had to compile from scratch using VS19.
I've updated both SimpleTrackingDemo and CompositeTrackingDemo and also added cmake targets for both.

**Comment by tttt0720** [comment]
Thanks!!  It seems that I need to recompile MTF, I'm going to do it right now. Thank you again.

**Comment by tttt0720** [comment]
Both `SimpleTrackingDemo` and `CompositeTrackingDemo` run successfully.
