### ISSUE TITLE
Compatibility with  OpenCV 3.4.15

### ISSUE THREAD

**Issue by atlas-jj** [abhineet123/MTF#21]
Hi Abhineet, 

I tried compile MTF with OpenCV 3.4.15 but got the following error:
![image](https://user-images.githubusercontent.com/36048272/125568672-9102cad6-595e-4135-ba68-4a951db11e83.png)

It seems the problem of newer openCV version. A discussion thread on the similar issue can be found [here](https://github.com/leggedrobotics/darknet_ros/issues/266#issuecomment-737075555): 

Looks like redefine the macro  -DCMAKE_CXX_FLAGS=-DCV__ENABLE_C_API_CTORS will solve the problem. That needs to modify the CMake file. Do you have any better ideas?

**Comment by abhineet123** [comment]
No, I haven't never tried to compile with opencv newer than 3.4.1. 
Most of these incompatibility issues are caused by outdated third party trackers so I simply turn them off with -DWITH_THIRD_PARTY=0

**Comment by atlas-jj** [comment]
Thanks. Adding -D WITH_THIRD_PARTY=0 to turn them off works. Maybe it's time to consider a lite version by removing those outdated trackers.

I will close this issue.
