### ISSUE TITLE
OpenCV 3.2/Ubuntu 16.10 - undefined references

### ISSUE THREAD

**Issue by kneczaj** [abhineet123/MTF#4]
After fixing https://github.com/abhineet123/MTF/issues/2, with same configuration I bumped on another error:

>Scanning dependencies of target extractPatch
[ 94%] Building CXX object CMakeFiles/extractPatch.dir/Examples/cpp/extractPatch.cc.o
[ 94%] Linking CXX executable extractPatch
[ 94%] Built target extractPatch
Scanning dependencies of target createMosaic
[ 95%] Building CXX object CMakeFiles/createMosaic.dir/Examples/cpp/createMosaic.cc.o
[ 95%] Linking CXX executable createMosaic
CMakeFiles/createMosaic.dir/Examples/cpp/createMosaic.cc.o: In function `mtf::TrackerBase* mtf::getTracker<mtf::MCPCA, mtf::Spline>(char const*, mtf::MCPCA::ParamType const*, mtf::Spline::ParamType const*)':
createMosaic.cc:(.text._ZN3mtf10getTrackerINS_5MCPCAENS_6SplineEEEPNS_11TrackerBaseEPKcPKNT_9ParamTypeEPKNT0_9ParamTypeE[_ZN3mtf10getTrackerINS_5MCPCAENS_6SplineEEEPNS_11TrackerBaseEPKcPKNT_9ParamTypeEPKNT0_9ParamTypeE]+0x2397): undefined reference to `mtf::FeatureTrackerParams::FeatureTrackerParams(int, int, int, int, bool, mtf::FeatureTrackerParams::DetectorType, mtf::FeatureTrackerParams::DescriptorType, bool, int, double, bool, bool, double, int, bool, bool, bool, bool)'
createMosaic.cc:(.text._ZN3mtf10getTrackerINS_5MCPCAENS_6SplineEEEPNS_11TrackerBaseEPKcPKNT_9ParamTypeEPKNT0_9ParamTypeE[_ZN3mtf10getTrackerINS_5MCPCAENS_6SplineEEEPNS_11TrackerBaseEPKcPKNT_9ParamTypeEPKNT0_9ParamTypeE]+0x23d5): undefined reference to `mtf::SIFTParams::SIFTParams(int, int, double, double, double)'
createMosaic.cc:(.text._ZN3mtf10getTrackerINS_5MCPCAENS_6SplineEEEPNS_11TrackerBaseEPKcPKNT_9ParamTypeEPKNT0_9ParamTypeE[_ZN3mtf10getTrackerINS_5MCPCAENS_6SplineEEEPNS_11TrackerBaseEPKcPKNT_9ParamTypeEPKNT0_9ParamTypeE]+0x2446): undefined reference to `mtf::FeatureTracker<mtf::Spline>::FeatureTracker(mtf::FeatureTrackerParams const*, mtf::SIFTParams const*, mtf::FLANNCVParams const*, mtf::SSMEstimatorParams const*, mtf::SplineParams const*)'

There is much more of the undefined references here, and this is just the beginning of the error message.

This happend with following cmake output:
> -- Boost version: 1.61.0
-- Found the following Boost libraries:
--   random
--   filesystem
--   system
-- Getting Eigen headers from: /usr/include/eigen3
-- Getting OpenCV headers from: /usr/local/include;/usr/local/include/opencv
-- Using OpenCV libraries: opencv_calib3d;opencv_core;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_aruco;opencv_bgsegm;opencv_bioinspired;opencv_ccalib;opencv_datasets;opencv_dnn;opencv_dpm;opencv_face;opencv_freetype;opencv_fuzzy;opencv_line_descriptor;opencv_optflow;opencv_phase_unwrapping;opencv_plot;opencv_reg;opencv_rgbd;opencv_saliency;opencv_stereo;opencv_structured_light;opencv_surface_matching;opencv_text;opencv_tracking;opencv_xfeatures2d;opencv_ximgproc;opencv_xobjdetect;opencv_xphoto
-- Getting Boost headers from: /usr/include
-- Getting Boost libraries from: /usr/lib/x86_64-linux-gnu
-- Using Boost libraries: /usr/lib/x86_64-linux-gnu/libboost_random.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_system.so
-- DFT disabled
-- PFSL3 disabled
-- Getting ViSP headers from: /usr/local/include;/usr/local/include;/usr/local/include/opencv;/usr/include/libxml2;/usr/include
-- Using ViSP libraries: visp_vs;visp_visual_features;visp_vision;visp_tt_mi;visp_tt;visp_me;visp_mbt;visp_klt;visp_blob;visp_sensor;visp_robot;visp_io;visp_gui;visp_detection;visp_core;visp_ar
-- GOTURN disabled
-- Xvision disabled
-- Enabled third party trackers: DSST/src/DSST;KCF/src/KCF;CMT/src/CMT;RCT/src/RCT;TLD/src/TLD;Struck/src/Struck;MIL/src/MIL;FRG/src/FRG;ViSP/src/ViSP
-- DFM disabled
-- Feature based grid tracker disabled
-- RegNet disabled
-- FLANN based NN is disabled
-- PYTHON_INCLUDE_DIRS: /usr/include/python2.7
-- PYTHON_LIBRARIES: /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- Could NOT find Matlab (missing:  Matlab_INCLUDE_DIRS Matlab_MEX_LIBRARY Matlab_MEX_EXTENSION MEX_COMPILER MX_LIBRARY) 
-- Matlab not found so mexMTF is disabled
        If Matlab is installed but not detected, mexMTF can be compiled by running the command in 'mtf_mex_cmd.txt' at the MATLAB prompt after:
         * removing all semi colons
         * replacing all occurences of the type '-l<full path to library>' with '<full path to library>'
         * replacing all occurences of the type '-l-L<path to library folder>' with '-L<path to library folder>'
-- MTF_COMPILETIME_FLAGS: -std=c++11
-- MTF_RUNTIME_FLAGS: -Wfatal-errors;-Wno-write-strings;-Wno-unused-result;-Wformat=0;-std=c++11;-O3;-msse2
-- MTF_DEFINITIIIONS: NDEBUG;EIGEN_NO_DEBUG;DISABLE_DFT;DISABLE_PFSL3;DISABLE_GOTURN;DISABLE_XVISION;DISABLE_DFM;DISABLE_GRID_FEAT;DISABLE_REGNET;DISABLE_FLANN;DISABLE_HDF5;DISABLE_SPI
-- CMAKE_CXX_FLAGS:  -fopenmp
-- CMAKE_C_FLAGS: 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kamil/dev/MTF/build_nn_feat

**Comment by abhineet123** [comment]
This should have been fixed after my last commit to resolve issue #2 .

**Comment by kneczaj** [comment]
Are you sure? It's a different file. However I build it from total scratch again. Let's see

**Comment by abhineet123** [comment]
Yes this too was caused by the pre-processor variable name being incorrect in the cmake file. This variable is used by all modules to decide if the feature module is enabled.

**Comment by kneczaj** [comment]
checked - works
