### ISSUE TITLE
Narrowing conversion compilation warnings

### ISSUE THREAD

**Issue by kneczaj** [abhineet123/MTF#5]
I have such warnings as below during compilation. Please decide if it matters, or they can be ignored.

>Scanning dependencies of target opentld
Building CXX object ThirdParty/TLD/CMakeFiles/opentld.dir/src/mftracker/BB.cpp.o
Building CXX object ThirdParty/TLD/CMakeFiles/opentld.dir/src/mftracker/BBPredict.cpp.o
Building CXX object ThirdParty/TLD/CMakeFiles/opentld.dir/src/mftracker/FBTrack.cpp.o
Building CXX object ThirdParty/TLD/CMakeFiles/opentld.dir/src/mftracker/Lk.cpp.o
Building CXX object ThirdParty/TLD/CMakeFiles/opentld.dir/src/mftracker/Median.cpp.o
Building CXX object ThirdParty/TLD/CMakeFiles/opentld.dir/src/Clustering.cpp.o
Building CXX object ThirdParty/TLD/CMakeFiles/opentld.dir/src/DetectionResult.cpp.o
Building CXX object ThirdParty/TLD/CMakeFiles/opentld.dir/src/DetectorCascade.cpp.o
Building CXX object ThirdParty/TLD/CMakeFiles/opentld.dir/src/EnsembleClassifier.cpp.o
Building CXX object ThirdParty/TLD/CMakeFiles/opentld.dir/src/ForegroundDetector.cpp.o
Building CXX object ThirdParty/TLD/CMakeFiles/opentld.dir/src/MedianFlowTracker.cpp.o
/home/kamil/dev/MTF/ThirdParty/TLD/src/MedianFlowTracker.cpp: In member function ‘void tld::MedianFlowTracker::track(const cv::Mat&, const cv::Mat&, cv::Rect*)’:
/home/kamil/dev/MTF/ThirdParty/TLD/src/MedianFlowTracker.cpp:67:39: warning: narrowing conversion of ‘prevBB->cv::Rect_<int>::x’ from ‘int’ to ‘float’ inside { } [-Wnarrowing]
         float bb_tracker[] = {prevBB->x, prevBB->y, prevBB->width + prevBB->x - 1, prevBB->height + prevBB->y - 1};
                               ~~~~~~~~^
/home/kamil/dev/MTF/ThirdParty/TLD/src/MedianFlowTracker.cpp:67:50: warning: narrowing conversion of ‘prevBB->cv::Rect_<int>::y’ from ‘int’ to ‘float’ inside { } [-Wnarrowing]
         float bb_tracker[] = {prevBB->x, prevBB->y, prevBB->width + prevBB->x - 1, prevBB->height + prevBB->y - 1};
                                          ~~~~~~~~^
/home/kamil/dev/MTF/ThirdParty/TLD/src/MedianFlowTracker.cpp:67:79: warning: narrowing conversion of ‘((prevBB->cv::Rect_<int>::width + prevBB->cv::Rect_<int>::x) - 1)’ from ‘int’ to ‘float’ inside { } [-Wnarrowing]
         float bb_tracker[] = {prevBB->x, prevBB->y, prevBB->width + prevBB->x - 1, prevBB->height + prevBB->y - 1};
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
/home/kamil/dev/MTF/ThirdParty/TLD/src/MedianFlowTracker.cpp:67:111: warning: narrowing conversion of ‘((prevBB->cv::Rect_<int>::height + prevBB->cv::Rect_<int>::y) - 1)’ from ‘int’ to ‘float’ inside { } [-Wnarrowing]
         float bb_tracker[] = {prevBB->x, prevBB->y, prevBB->width + prevBB->x - 1, prevBB->height + prevBB->y - 1};
                                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~

**Comment by abhineet123** [comment]
These shouldn't matter.
